default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: darts_development

test: &test
  <<: *default
  database: darts_test

production:
  <<: *default
  database: darts_production
