# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8306b8b708ecd407fb9693a81777ac69565657d5efb828bb76897535ff8a024ec7904f2a097f93b35accf3bf34a1cf33fa1295cd333fc15a87490a16ec5719

test:
  secret_key_base: ef3206a1885bda1f8fe46493a8eee0d7f1d15d949a172b09cfc1cd55cc39ebb54ff6cb1eaae705bb0da19586c0c669a65c8142f492bf80fd990336d40f74dfaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
